#!/bin/sh
# This file is autogenerated - DO NOT EDIT!
set -euo pipefail
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${BASE_DIR}/.."
(
cd ${REPO_DIR}
helm uninstall mq-redis -n mq
helm uninstall mq-rabbitmq -n mq
kubectl delete pvc --all -n mq
kubectl delete namespace mq
)
