#!/bin/sh
# This file is autogenerated - DO NOT EDIT!
set -euo pipefail
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${BASE_DIR}/.."
(
cd ${REPO_DIR}
kubectl create namespace mq --dry-run=client -o yaml | kubectl apply -f -
helm repo add bitnami https://charts.bitnami.com/bitnami
helm upgrade --install mq-rabbitmq bitnami/rabbitmq -n mq -f rabbitmq/values.yaml
helm upgrade --install mq-redis bitnami/redis -n mq -f redis/values.yaml
)
